[hostname]
ssh_only = false
suffix = ""
disabled = false

[username]
show_always = true

[git_status]
show_sync_count = true
untracked_count.enabled = true
conflicted_count.enabled = true
modified_count.enabled = true
staged_count.enabled = true
renamed_count.enabled = true
delected_count.enabled = true

[directory]
truncate_to_repo = false

[rust]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true