# Dirs
config = "~/.config"
ssh = "~/.ssh"

"bash_aliases.sh" = "~/.bash_aliases"
"bash_prompt.sh" = "~/.bash_prompt"
"bashrc.sh" = "~/.bashrc"
"bashrc_default.sh" = "~/.bashrc_default"
"zpass.bash-completion.sh" = "~/.zpass.bash-completion"

gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"
inputrc = "~/.inputrc"
pylintrc = "~/.pylintrc"

"mozilla/MaterialFox/chrome" = "~/.mozilla/firefox/vlfr4wgj.default/chrome"