# Dirs
config = "~/.config"
ssh = "~/.ssh"

bash_aliases = "~/.bash_aliases"
bash_prompt = "~/.bash_prompt"
bashrc = "~/.bashrc"
bashrc_default = "~/.bashrc_default"
gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"
inputrc = "~/.inputrc"
pylintrc = "~/.pylintrc"
  