# Dirs
config = "~/.config"
ssh = "~/.ssh"

"bashrc.sh" = "~/.bashrc"
"bashrc_default.sh" = "~/.bashrc_default"
"bash_aliases.sh" = "~/.bash_aliases"
"bash_prompt.sh" = "~/.bash_prompt"
"bash_completion.sh" = "~/.bash_completion"

gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"
inputrc = "~/.inputrc"
pylintrc = "~/.pylintrc"

# "mozilla/MaterialFox/chrome" = "~/.mozilla/firefox/vlfr4wgj.default/chrome"