bash_aliases = "~/.bashrc_default"
bash_prompt = "~/.bash_prompt"
bashrc = "~/.bashrc"
bashrc_default = "~/.bashrc_default"
gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"
inputrc = "~/.inputrc"
pylintrc = "~/.pylintrc"
config = "~/.config"
